/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Clean old caches
cleanupOutdatedCaches();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// ----------------------------------------------------------------------
// Caching strategies (migrated from vite.config.ts)
// ----------------------------------------------------------------------

// Cache Fontshare fonts
registerRoute(
  /^https:\/\/api\.fontshare\.com\/.*/i,
  new CacheFirst({
    cacheName: 'fontshare-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Cache Google Fonts stylesheets
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' })
);

// Cache Google Fonts webfonts
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Cache API requests (NetworkFirst for fresh data, fallback to cache)
registerRoute(
  /\/api\/(categories|resources|me)/i,
  new NetworkFirst({
    cacheName: 'knowhere-api-cache',
    networkTimeoutSeconds: 3,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 7 }),
    ],
  })
);

// ----------------------------------------------------------------------
// Push Notifications
// ----------------------------------------------------------------------

self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push event received:', event);
  if (!event.data) {
    console.warn('[Service Worker] Push event contains no data.');
    return;
  }
  
  const showPushNotification = async () => {
    try {
      const text = event.data!.text();
      console.log('[Service Worker] Raw push payload text:', text);
      
      let data;
      try {
        data = event.data!.json();
        console.log('[Service Worker] Parsed push JSON:', data);
      } catch (jsonErr) {
        console.error('[Service Worker] Failed to parse push payload as JSON. Using raw text:', jsonErr);
        data = { title: 'Knowhere', body: text };
      }
      
      const title = data.title || 'Knowhere';
      const options = {
        body: data.body || '',
        icon: '/push-icon.svg',
        badge: '/notification-badge.svg',
        vibrate: [200, 100, 200],
        silent: false,
        data: { url: data.url || '/', ackToken: data.ackToken },
        requireInteraction: true // Keeps notification visible until clicked or dismissed
      };

      console.log('[Service Worker] Attempting to show notification:', title, options);

      try {
        await self.registration.showNotification(title, options);
        console.log('[Service Worker] showNotification succeeded.');
      } catch (innerErr) {
        console.error('[Service Worker] showNotification failed with full options, retrying with basic options:', innerErr);
        // Fallback: remove requireInteraction to avoid platform-specific errors
        await self.registration.showNotification(title, {
          body: options.body,
          icon: options.icon,
          badge: options.badge,
          vibrate: options.vibrate,
          silent: false,
          data: options.data
        } as any);
        console.log('[Service Worker] showNotification (fallback basic) succeeded.');
      }
    } catch (err) {
      console.error('[Service Worker] Critical error in push event handler:', err);
    }
  };

  event.waitUntil(showPushNotification());
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;
  const ackToken = event.notification.data.ackToken;

  event.waitUntil(
    Promise.all([
      // 1. Acknowledge the click (fire-and-forget)
      ackToken
        ? fetch('/api/push/ack', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ ackToken }),
          }).catch((err) => console.error('[SW] Failed to ack notification click', err))
        : Promise.resolve(),
        
      // 2. Navigate to the resource
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
        // If window already open, focus it and navigate
        for (let i = 0; i < windowClients.length; i++) {
          const client = windowClients[i];
          if (client.url.startsWith(self.location.origin) && 'focus' in client) {
            client.focus();
            return client.navigate(urlToOpen);
          }
        }
        // If no window open, open new one
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
    ])
  );
});
